"""
OBD Data Loader — Adapter for the Open Bandit Dataset (ZOZO).

Loads the preprocessed OBD dataset and exposes a clean iterable interface
compatible with the project's agent/evaluation pipeline.
"""

import json
import os
from typing import Generator, Optional

import numpy as np


class OBDDataLoader:
    """
    Loads the Open Bandit Dataset from disk and provides a simple iterable
    interface compatible with the project's IPSEvaluator.

    Expected file: data/obd/obd_bandit_feedback.npz
    Generated by:  scripts/download_obd.py
    """

    def __init__(
        self,
        data_path: str = "data/obd/obd_bandit_feedback.npz",
        stats_path: str = "data/obd/obd_stats.json",
    ):
        if not os.path.exists(data_path):
            raise FileNotFoundError(
                f"OBD dataset not found at '{data_path}'.\n"
                "Run: python scripts/download_obd.py"
            )

        data = np.load(data_path, allow_pickle=True)

        self._context = data["context"]  # (n, d)
        self._action = data["action"].astype(int)  # (n,)
        self._reward = data["reward"].astype(float)  # (n,)
        self._pscore = data["pscore"].astype(float)  # (n,)
        self._n_actions = int(data["n_actions"][0])

        # Action context (item features) — may not exist in all OBD versions
        self._action_context: Optional[np.ndarray] = None
        if "action_context" in data:
            self._action_context = data["action_context"]  # (K, d_a)

        # Load stats
        if os.path.exists(stats_path):
            with open(stats_path) as f:
                self._stats = json.load(f)
        else:
            self._stats = {}

        # Validate
        assert self._pscore.min() > 0, "Propensity scores must be strictly positive!"
        assert (
            len(self._context)
            == len(self._action)
            == len(self._reward)
            == len(self._pscore)
        )

    # ------------------------------------------------------------------ #
    #  Properties                                                          #
    # ------------------------------------------------------------------ #

    @property
    def n_events(self) -> int:
        """Total number of logged interaction events."""
        return len(self._context)

    @property
    def n_actions(self) -> int:
        """Number of distinct items/arms (K)."""
        return self._n_actions

    @property
    def context_dim(self) -> int:
        """Dimension of the user/context feature vector."""
        return self._context.shape[1]

    @property
    def action_context_dim(self) -> int:
        """Dimension of action (item) feature vector, 0 if not available."""
        if self._action_context is not None:
            return self._action_context.shape[1]
        return 0

    @property
    def baseline_ctr(self) -> float:
        """Observed CTR of the logging policy (Random)."""
        return float(self._reward.mean())

    @property
    def has_action_context(self) -> bool:
        return self._action_context is not None

    def get_action_embedding(self, arm_idx: int) -> np.ndarray:
        """
        Returns the feature vector for item arm_idx.
        If action_context is available: return actual item features.
        Else: return a one-hot vector of dimension n_actions (fallback).
        """
        if self._action_context is not None and arm_idx < len(self._action_context):
            return self._action_context[arm_idx].astype(float)
        # Fallback: one-hot
        one_hot = np.zeros(self._n_actions, dtype=float)
        if 0 <= arm_idx < self._n_actions:
            one_hot[arm_idx] = 1.0
        return one_hot

    def get_all_action_embeddings(self) -> dict:
        """Returns {arm_idx: embedding} for all arms."""
        return {arm: self.get_action_embedding(arm) for arm in range(self._n_actions)}

    # ------------------------------------------------------------------ #
    #  Event access                                                        #
    # ------------------------------------------------------------------ #

    def get_event(self, t: int) -> dict:
        """
        Returns event t as a dict:
            context        : np.ndarray (d,)   — user/context features
            logged_action  : int               — action chosen by logging policy
            reward         : float             — observed reward (0/1 click)
            pscore         : float             — P(a|x, π₀)
        """
        return {
            "context": self._context[t],
            "logged_action": int(self._action[t]),
            "reward": float(self._reward[t]),
            "pscore": float(self._pscore[t]),
        }

    def iterate(self) -> Generator[dict, None, None]:
        """Iterator over all logged events."""
        for t in range(self.n_events):
            yield self.get_event(t)

    def __len__(self) -> int:
        return self.n_events

    def __repr__(self) -> str:
        return (
            f"OBDDataLoader("
            f"n_events={self.n_events:,}, "
            f"n_actions={self.n_actions}, "
            f"context_dim={self.context_dim}, "
            f"baseline_ctr={self.baseline_ctr:.4f}, "
            f"has_action_context={self.has_action_context})"
        )
